artifact_location: file:///C:/Users/DEBANJAN SHIL/Documents/Churn_Prediction/mlflow/563500302151887607
creation_time: 1747972059319
experiment_id: '563500302151887607'
last_update_time: 1747972059319
lifecycle_stage: active
name: churn_prediction_experiment
